---

- name: Vector | Install package for CentOS
  become: true
  ansible.builtin.yum:
    name: "{{ vector_url_rpm }}"
    state: present
    disable_gpg_check: true
  when: ansible_distribution == "CentOS"

- name: Vector | Install package for Ubuntu
  become: true
  ansible.builtin.apt:
    deb: "{{ vector_url_deb }}"
  when: ansible_distribution == "Ubuntu"
  - name: Vector | Configure vector
  template:
    src: vector.yml.j2
    dest: vector.yml
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
  notify: start_vector
- name: Vector | create systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: "644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
